{'_time': '2022-10-06 11:02:09.982 EDT', 'sourcetype': 'splunkd', '_raw': '10-06-2022 11:02:09.982 -0400 ERROR ExecProcessor [10663413 ExecProcessor] - message from "/Applications/Splunk/bin/python3.7 /Applications/Splunk/etc/apps/splunk_assist/bin/selfupdate_modular_input.py" .'}
{'_time': '2022-10-06 11:02:09.982 EDT', 'sourcetype': 'splunkd', '_raw': '10-06-2022 11:02:09.982 -0400 ERROR ExecProcessor [10663413 ExecProcessor] - message from "/Applications/Splunk/bin/python3.7 /Applications/Splunk/etc/apps/splunk_assist/bin/selfupdate_modular_input.py" splunk.AuthenticationFailed: [HTTP 401] Client is not authenticated'}
{'_time': '2022-10-06 11:02:09.981 EDT', 'sourcetype': 'splunkd', '_raw': '10-06-2022 11:02:09.981 -0400 ERROR ExecProcessor [10663413 ExecProcessor] - message from "/Applications/Splunk/bin/python3.7 /Applications/Splunk/etc/apps/splunk_assist/bin/selfupdate_modular_input.py"     raise splunk.AuthenticationFailed'}
{'_time': '2022-10-06 11:02:09.981 EDT', 'sourcetype': 'splunkd', '_raw': '10-06-2022 11:02:09.981 -0400 ERROR ExecProcessor [10663413 ExecProcessor] - message from "/Applications/Splunk/bin/python3.7 /Applications/Splunk/etc/apps/splunk_assist/bin/selfupdate_modular_input.py"   File "/Applications/Splunk/lib/python3.7/site-packages/splunk/rest/__init__.py", line 625, in simpleRequest'}
{'_time': '2022-10-06 11:02:09.981 EDT', 'sourcetype': 'splunkd', '_raw': '10-06-2022 11:02:09.981 -0400 ERROR ExecProcessor [10663413 ExecProcessor] - message from "/Applications/Splunk/bin/python3.7 /Applications/Splunk/etc/apps/splunk_assist/bin/selfupdate_modular_input.py"     raiseAllErrors=True'}
{'_time': '2022-10-06 11:02:09.980 EDT', 'sourcetype': 'splunkd', '_raw': '10-06-2022 11:02:09.980 -0400 ERROR ExecProcessor [10663413 ExecProcessor] - message from "/Applications/Splunk/bin/python3.7 /Applications/Splunk/etc/apps/splunk_assist/bin/selfupdate_modular_input.py"   File "/Applications/Splunk/etc/apps/splunk_assist/bin/assist/serverinfo.py", line 279, in get_telemetry_sud_optin'}
{'_time': '2022-10-06 11:02:09.980 EDT', 'sourcetype': 'splunkd', '_raw': '10-06-2022 11:02:09.980 -0400 ERROR ExecProcessor [10663413 ExecProcessor] - message from "/Applications/Splunk/bin/python3.7 /Applications/Splunk/etc/apps/splunk_assist/bin/selfupdate_modular_input.py"     telemetry_sud_optin = get_telemetry_sud_optin(log, session_key)'}
{'_time': '2022-10-06 11:02:09.979 EDT', 'sourcetype': 'splunkd', '_raw': '10-06-2022 11:02:09.979 -0400 ERROR ExecProcessor [10663413 ExecProcessor] - message from "/Applications/Splunk/bin/python3.7 /Applications/Splunk/etc/apps/splunk_assist/bin/selfupdate_modular_input.py"   File "/Applications/Splunk/etc/apps/splunk_assist/bin/assist/serverinfo.py", line 373, in is_assist_enabled'}
{'_time': '2022-10-06 11:02:09.978 EDT', 'sourcetype': 'splunkd', '_raw': '10-06-2022 11:02:09.978 -0400 ERROR ExecProcessor [10663413 ExecProcessor] - message from "/Applications/Splunk/bin/python3.7 /Applications/Splunk/etc/apps/splunk_assist/bin/selfupdate_modular_input.py"     sud = is_assist_enabled(log, session_key)'}
{'_time': '2022-10-06 11:02:09.978 EDT', 'sourcetype': 'splunkd', '_raw': '10-06-2022 11:02:09.978 -0400 ERROR ExecProcessor [10663413 ExecProcessor] - message from "/Applications/Splunk/bin/python3.7 /Applications/Splunk/etc/apps/splunk_assist/bin/selfupdate_modular_input.py"   File "/Applications/Splunk/etc/apps/splunk_assist/bin/selfupdate_modular_input.py", line 57, in should_run'}
